### ISSUE TITLE
VersionBot: Allow omitting versioning using commit footer tags

### ISSUE THREAD

**Issue by jviotti** [balena-io-modules/balena-procbots#60]
Procbots require adding a label when creating a pull request when you want the service to omit its checks. I use the `hub` tool, which as a `pull-request` command to automatically create the pull request, so the label approach might be tricky for me..

Maybe we can also make it check a footer tag?

It could go and check the commits, and if the footer tag is present, report that everything is correct without doing any further checks.

**Comment by lurch** [comment]
What would be the equivalent to 'removing' the label in that case?

**Comment by jviotti** [comment]
If you decided that ProcBots should not mess with certain commits, then you don't care about the labeling anymore, right?

**Comment by lurch** [comment]
Ahh, I guess I'd always seen the `procbots/versionbot/no-checks` as a "this PR is a work-in-progress, please don't run any checks on it yet" label, which you'd then remove when the PR was more polished, and you did want the checks to run?

**Comment by jviotti** [comment]
Closing stale issues
